USE ProyectoBases;
GO

--3.	Deben construirse al menos 3 esquemas en los cuales se dividan las tablas propuestas 
CREATE SCHEMA application_train;
GO

CREATE SCHEMA bureau;
GO

CREATE SCHEMA previous;
GO

--Primer esquema
ALTER SCHEMA application_train TRANSFER dbo.APPLICATION_TRAIN;
ALTER SCHEMA application_train TRANSFER dbo.CUSTOMER_APPLICATION_TRAIN;
ALTER SCHEMA application_train TRANSFER dbo.PROPERTIES_CUSTOMERS_APPLICATION_TRAIN;
ALTER SCHEMA application_train TRANSFER dbo.CONTACT_CUSTOMER_APPLICATION_TRAIN;
ALTER SCHEMA application_train TRANSFER dbo.AMT_REQUEST_APPLICATION_TRAIN;
ALTER SCHEMA application_train TRANSFER dbo.REGION_QUALIFICATION_APPLICATION_TRAIN;
ALTER SCHEMA application_train TRANSFER dbo.BUILD_COSTUMER_AVG_APPLICATION_TRAIN;
ALTER SCHEMA application_train TRANSFER dbo.BUILD_COSTUMER_MODE_APPLICATION_TRAIN;
ALTER SCHEMA application_train TRANSFER dbo.BUILD_COSTUMER_MEDI_APPLICATION_TRAIN;
ALTER SCHEMA application_train TRANSFER dbo.CUSTUMER_CUSTOMER_APPLICATION_TRAIN;
ALTER SCHEMA application_train TRANSFER dbo.DOCUMENT_APLICATION_TRAIN;
ALTER SCHEMA application_train TRANSFER dbo.EXT_SOURCES_APPLICATION_TRAIN;

--Segundo esquema
ALTER SCHEMA bureau TRANSFER dbo.BUREAU;
ALTER SCHEMA bureau TRANSFER dbo.BUREAU_BALANCE;
ALTER SCHEMA bureau TRANSFER dbo.CREDIT_AMOUNTS_BUREAU;
ALTER SCHEMA bureau TRANSFER dbo.CREDIT_TIMELINE_BUREAU;


--Tercer esquema
ALTER SCHEMA previous TRANSFER dbo.PREVIOUS_APPLICATION;
ALTER SCHEMA previous TRANSFER dbo.INTEREST_RATES_PREVIOUS_APPLICATION;
ALTER SCHEMA previous TRANSFER dbo.AMT_PREVIOUS_APPLICATION;
ALTER SCHEMA previous TRANSFER dbo.LOAN_TERMS_PREVIOUS_APPLICATION;
ALTER SCHEMA previous TRANSFER dbo.CREDIT_CARD_BALANCED;
ALTER SCHEMA previous TRANSFER dbo.CREDIT_CARD_DRAWINGS;
ALTER SCHEMA previous TRANSFER dbo.INSTALLMENTS_PAYMENT;
ALTER SCHEMA previous TRANSFER dbo.POS_CASH_BALANCE;


