--9.	Deben construir al menos 5 índices no clúster. 5pts 


CREATE NONCLUSTERED INDEX info_customer_app
ON [application_train].[CUSTOMER_APPLICATION_TRAIN]
([ID] ASC, [CODE_GENDER])
INCLUDE ([CNT_CHILDREN]
      ,[NAME_TYPE_SUITE]
      ,[NAME_INCOME_TYPE]
      ,[NAME_EDUCATION_TYPE]
      ,[NAME_FAMILY_STATUS]
      ,[NAME_HOUSING_TYPE]
      ,[DAYS_BIRTH]
      ,[DAYS_EMPLOYED]
      ,[OCCUPATION_TYPE]
      ,[CNT_FAM_MEMBERS]
      ,[ORGANIZATION_TYPE]
      ,[ID_PERSONAL_CONTACT]
      ,[ID_PERSONAL_PROPERTIES]
      ,[ID_REGION_QUALIFICATION_CUSTOMERS]
      ,[ID_CUSTUMER_CUSTOMER]);
	 

CREATE NONCLUSTERED INDEX idx_bureau_info
ON [bureau].[BUREAU]
(
    [SK_ID_BUREAU] ASC,
    [CREDIT_ACTIVE] ASC,
    [CREDIT_CURRENCY] ASC,
	[CNT_CREDIT_PROLONG] ASC,
	[CREDIT_TYPE] ASC,
    [SK_ID_CURR] ASC,
	[ID_CREDIT_TIMELINE] ASC,
    [ID_CREDIT_AMOUNTS] ASC
);

CREATE NONCLUSTERED INDEX idx_previous_application_info
ON [previous].[PREVIOUS_APPLICATION]
(
    [SK_ID_PREV] ASC,
    [NAME_CONTRACT_TYPE] ASC,
    [WEEKDAY_APPR_PROCESS_START] ASC,
    [HOUR_APPR_PROCESS_START] ASC,
    [FLAG_LAST_APPL_PER_CONTRACT] ASC,
    [NFLAG_LAST_APPL_IN_DAY] ASC,
    [NAME_CASH_LOAN_PURPOSE] ASC,
    [NAME_CONTRACT_STATUS] ASC,
    [DAYS_DECISION] ASC,
    [NAME_PAYMENT_TYPE] ASC,
    [CODE_REJECT_REASON] ASC,
    [NAME_TYPE_SUITE] ASC,
    [NAME_CLIENT_TYPE] ASC,
	[NAME_GOODS_CATEGORY]	ASC,
    [NAME_PORTFOLIO] ASC,
    [NAME_PRODUCT_TYPE] ASC,
    [CHANNEL_TYPE] ASC,
    [SELLERPLACE_AREA] ASC,
    [NAME_SELLER_INDUSTRY] ASC,
    [CNT_PAYMENT]	ASC,
    [NAME_YIELD_GROUP] ASC,
    [PRODUCT_COMBINATION]	ASC,
    [ID_INTEREST_RATES] ASC,
    [ID_AMT_PREVIOUS]	ASC,
    [ID_LOAN_TERMS] ASC,
    [SK_ID_CURR] ASC
);

CREATE NONCLUSTERED INDEX idx_credit_card_balance_info
ON [previous].[CREDIT_CARD_BALANCED]
(
	[SK_ID_CURR] ASC,
    [MONTHS_BALANCE] ASC,
    [AMT_BALANCE] ASC,
    [AMT_CREDIT_LIMIT_ACTUAL] ASC,
    [AMT_INST_MIN_REGULARITY] ASC,
    [AMT_PAYMENT_CURRENT] ASC,
    [AMT_PAYMENT_TOTAL_CURRENT] ASC,
    [AMT_RECEIVABLE_PRINCIPAL] ASC,
    [AMT_RECIVABLE] ASC,
    [AMT_TOTAL_RECEIVABLE] ASC,
    [CNT_INSTALMENT_MATURE_CUM] ASC,
    [NAME_CONTRACT_STATUS] ASC,
	[SK_DPD] ASC,
    [SK_DPD_DEF] ASC,
    [ID_CREDIT_CARD_DRAWINGS] ASC,
    [SK_ID_PREV] ASC
);

CREATE NONCLUSTERED INDEX idx_bureau_balance_info
ON [bureau].BUREAU_BALANCE
(
    [ID] ASC,
    [SK_ID_BUREAU] ASC,
    [MONTHS_BALANCE] ASC,
    [STATUS] ASC
);